- name: Include http section
  lineinfile:
    path: "/etc/nginx/nginx.conf"
    line: "include /etc/nginx/nginx_http.conf;"
    state: present
  register: _include_http
  notify:
    - restart nginx

#- name: check nginx_http.conf
#  stat: 
#    path: /etc/nginx/nginx_http.conf
#    register: _http_file_exist

- name: Create nginx_http.conf
  template: 
    src: nginx_http.conf.j2
    dest: "/etc/nginx/nginx_http.conf"
    owner: "root"
    group: "root"
    mode: "0644"
#  when: not _http_file_exists.stat.exists
  notify:
    - restart nginx

- name: Create nginx Proxy master settings
  template: 
    src: proxy_master.conf.j2
    dest: "/etc/nginx/conf.d/proxy_{{item.server_name}}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{nginx_proxy_master}}"
  notify:
    - restart nginx

- name: Create directory for Proxy settings
  file: 
    path: "/etc/nginx/conf.d/proxy"
    state: directory
    owner: "root"
    group: "root"
    mode: "0644"

- name: Create nginx Proxy settings for kibana
  template: 
    src: proxy_template.conf.j2
    dest: "/etc/nginx/conf.d/proxy/proxy_{{item.proxy_name}}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{nginx_proxy_hosts}}"
  notify:
    - restart nginx

- name: Create nginx Proxy list
  template: 
    src: proxylist.conf.j2
    dest: "/etc/nginx/conf.d/proxylist_{{item.proxy_name}}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    force: no
  with_items: "{{nginx_proxy_hosts}}"
  notify:
    - restart nginx

- name: List Up Proxy Backends
  lineinfile:
    path: "/etc/nginx/conf.d/proxylist_{{item.0.proxy_name}}.conf"
    insertbefore: '^}$'
    line: "server {{item.1}};"
  with_subelements:
    - "{{nginx_proxy_hosts}}"
    - serverlist
    - flags:
        skip_missing: True
  notify:
    - restart nginx


